---
- hosts: all
  become: true
  tasks:
    - name: Update package cache and install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: true

    - name: Copy website files to Nginx root directory
      ansible.builtin.copy:
        src: coffee-shop/
        dest: /var/www/html/
        owner: root
        group: root
        mode: '0755'
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
