---
# tasks file for role1
- name: Update package cache and install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
- name: Start and enable Nginx service
  service:
    name: nginx
    state: started
    enabled: true
- name: Copy website files to Nginx root directory
  ansible.builtin.copy:
    src: files/coffee-shop/
    dest: /var/www/html/
    owner: root
    group: root
    mode: '0755'
  notify: Restart Nginx 
